Added entry in changelog
git-svn-id: svn://svn.code.sf.net/p/parcellite/code/trunk@28 b25b1718-469e-46af-be73-919d414b4ebe

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2293,7 +2293,7 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
-ALL_LINGUAS="de es it ru"
+ALL_LINGUAS="de es hu it ru"
 DEPDIR="${am__leading_dot}deps"
 
 ac_config_commands="$ac_config_commands depfiles"
@@ -9588,8 +9588,8 @@ rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
      fi
      GTK_CFLAGS=""
      GTK_LIBS=""
-     { { echo "$as_me:$LINENO: error: requirement not met: gtk >= 2.10.0" >&5
-echo "$as_me: error: requirement not met: gtk >= 2.10.0" >&2;}
+     { { echo "$as_me:$LINENO: error: Requirement not met: gtk >= 2.10.0" >&5
+echo "$as_me: error: Requirement not met: gtk >= 2.10.0" >&2;}
    { (exit 1); exit 1; }; }
   fi
 
@@ -9993,8 +9993,8 @@ rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
      GLIB_GENMARSHAL=""
      GOBJECT_QUERY=""
      GLIB_MKENUMS=""
-     { { echo "$as_me:$LINENO: error: requirement not met: glib >= 2.14.0" >&5
-echo "$as_me: error: requirement not met: glib >= 2.14.0" >&2;}
+     { { echo "$as_me:$LINENO: error: Requirement not met: glib >= 2.14.0" >&5
+echo "$as_me: error: Requirement not met: glib >= 2.14.0" >&2;}
    { (exit 1); exit 1; }; }
   fi
 
